use sakila
select * from film
#1.Retrieve the total revenue generated for each film category.
select fc.category_id, sum(p.amount) as 'Total Revenue' from film_category fc 
join film f on fc.film_id=f.film_id 
join inventory i on i.film_id=f.film_id
join rental r on r.inventory_id=i.inventory_id 
join payment p on p.rental_id=r.rental_id group by fc.category_id;

#2.Determine the count of rentals for each customer.
select count(r.rental_id),c.customer_id from rental r
join customer c on c.customer_id = r.customer_id group by customer_id

#3.Calculate the average rental duration (in days) for each film.
select film_id, avg(rental_duration) from film group by film_id 

#4. Find the total revenue generated for each month.
select month(payment_date),sum(p.amount) as 'Total Revenue'from payment p
group by month(payment_date)

#5. Determine the total revenue generated by each store.
select st.store_id,sum(p.amount)as 'Total Revenue' from payment p 
join staff s on s.staff_id = p.staff_id
join store st on st.store_id = s.store_id group by st.store_id

#6. Calculate the count of rentals handled by each staff member.
select s.staff_id,count(r.rental_id) as 'No. of Rentals' from rental r
join staff s on s.staff_id = r.staff_id
join store st on st.store_id = s.store_id group by s.staff_id

#7.Compute the average rental rate for each film category.
select f.film_id,avg(f.rental_rate) as 'ARR' from film f
join film_category fc on fc.film_id = f.film_id group by f.film_id

#8.Determine the count of rentals for each film.
select f.film_id,count(r.rental_id) as 'Total Rentals' from film f
join inventory i on i.film_id = f.film_id 
join rental r on r.inventory_id = i.inventory_id group by  f.film_id

#9.Retrieve the total revenue generated for each city.
select ct.city, sum(p.amount)
from city ct join address ad on ct.city_id=ad.city_id
join staff st on ad.address_id=st.address_id
join payment p on st.staff_id=p.staff_id
group by ct.city

#10. Calculate the count of rentals for each film language.
select  l.name ,count(r.rental_id) from rental r
join inventory i on r.inventory_id = i.inventory_id
join film f on i.film_id = f.film_id
join language l on f.language_id = l.language_id group by l.name order by l.name;
